const LETTERS = {
  אֶיי: "A",
  בִּי: "B",
  סי: "C",
  די: "D",
  אִי: "E",
  אף: "F",
  "גִ'י": "G",
  אייץ: "H",
  "גֶ'יי": "J",
  קיי: "K",
  אל: "L",
  אם: "M",
  אן: "N",
  או: "O",
  פי: "P",
  קיו: "Q",
  אר: "R",
  אס: "S",
  טי: "T",
  יו: "U",
  וי: "V",
  דבליו: "W",
  אקס: "X",
  וויי: "Y",
  זד: "Z",
  "אֶיי קטנה": "a",
  "בִּי קטנה": "b",
  "סי קטנה": "c",
  "די קטנה": "d",
  "אִי קטנה": "e",
  "אף קטנה": "f",
  "גִ'י קטנה": "g",
  "אייץ קטנה": "h",
  "ג'יי קטנה": "j",
  "קיי קטנה": "k",
  "אל קטנה": "l",
  "אם קטנה": "m",
  "אן קטנה": "n",
  "או קטנה": "o",
  "פי קטנה": "p",
  "קיו קטנה": "q",
  "אר קטנה": "r",
  "אס קטנה": "s",
  "טי קטנה": "t",
  "יו קטנה": "u",
  "וי קטנה": "v",
  "דבליו קטנה": "w",
  "אקס קטנה": "x",
  "וויי קטנה": "y",
  "זד קטנה": "z",
};

const SOUNDS1 = {
  בַּאבּ: "bab",
  בֶּבּ: "beb",
  בִּיבּ: "bib",
  בּוֹבּ: "bob",
  בּוּבּ: "bub",
  רַאר: "rar",
  רֶר: "rer",
  רִיר: "rir",
  רוֹר: "ror",
  רוּר: "rur",
  לַל: "lal",
  לֶל: "lel",
  לִיל: "lil",
  לוֹל: "lol",
  לוּל: "lul",
  מַאם: "mam",
  מֶמ: "mem",
  מִים: "mim",
  מוֹם: "mom",
  מוּם: "mum",
  קַאקּ: "kak",
  קֶקּ: "kek",
  קִיקּ: "kik",
  קּוֹקּ: "kok",
  קּוּקּ: "kuk",
  תַאת: "tat",
  תֶת: "tet",
  תִית: "tit",
  תוֹת: "tot",
  תוּת: "tut",
  פַאפ: "faf",
  פֶפ: "fef",
  פִיפ: "fif",
  פַּפ: "pap",
  פֶּפ: "pep",
  פִּיפ: "pip",
  פּוֹפּ: "pop",
  פּוּפּ: "pup",
  סַאס: "sas",
  סֶס: "ses",
  סִיס: "sis",
  סוֹס: "sos",
  סוּס: "sus",
  זַאז: "zaz",
  זֶז: "zez",
  זִיז: "ziz",
  זוֹז: "zoz",
  זוּז: "zuz",
  וַאו: "vav",
  וֶו: "vev",
  וִיו: "viv",
  ווֹו: "vov",
  ווּו: "vuv",
  גַאג: "gag",
  גֶג: "geg",
  גִיג: "gig",
  גוֹג: "gog",
  גוּג: "gug",
  "ג׳ַאג׳": "jaj",
  "ג׳ֶג׳": "jej",
  "ג׳ִיג׳": "jij",
  "ג׳וֹג׳": "joj",
  "ג׳וּג׳": "juj",
};

const SOUNDS2 = {
  "day (יום)": "דֵי",
  "dim (כהה)": "דִים",
  "dip (לטבול)": "דִיפ",
  "dog (כֶּלֶב)": "דוֹג",
  "dot (נְקוּדָה)": "דוֹט",
  "dry (יָבֵשׁ)": "דְרַי",
  "dad (אַב)": "דַּד",
  "did (עָשָׂה)": "דִיד",
  "dig (חָפַר)": "דִיג",
  "dug (חָפַר)": "דַג",
  "dab (לַעֲטוֹת)": "דַב",
  "den (מְנוּי)": "דֶן",
  "dew (טַל)": "דֵו",
  "dam (סְכָר)": "דַם",
  "dye (לְצַבֵּעַ)": "דַי",
  "dud (בחור)": "דֻד",
  "act (פְּעִולָה)": "אַקְט",
  "add (לְהוֹסִיף)": "אַד",
  "age (גִּיל)": "אֵיג",
  "aim (מֶטָה)": "אֵים",
  "air (אֲוִיר)": "אֵיר",
  "all (הַכֹּל)": "אוֹל",
  "and (וְ)": "אַנד",
  "any (כָּל)": "אֵנִי",
  "apt (כָּשֵׁר)": "אַפְט",
  "arm (זְרוֹעַ)": "אַרְמ",
  "art (אוּמָנוּת)": "אַרְט",
  "ask (לִשְׁאוֹל)": "אַסְק",
  "bad (רַע)": "בַּד",
  "bag (תִּיק)": "בַּג",
  "bar (בָּר)": "בַּר",
  "bat (מַלְקָט)": "בַּט",
  "bed (מִטָּה)": "בֵּד",
  "bet (לְהִתְעַרֵב)": "בֵּט",
  "big (גָּדוֹל)": "בִּיג",
  "bit (מַעֲט)": "בִּיט",
  "box (קופסא)": "בוקס",
  "boy (ילד)": "בוֹי",
  "bug (מַקֵּק)": "בַּג",
  "buy (לִקְנוֹת)": "בוּי",
  "can (יָכוֹל)": "קַן",
  "cap (כובע)": "קַפְפ",
  "car (מְכוֹנִית)": "קַר",
  "cat (חָתוּל)": "קַט",
  "cop (שוטר)": "קַפְפ",
  "cow (פָּרָה)": "קַו",
  "cry (לִבְכוֹת)": "קַרִי",
  "cup (סְפּוֹג)": "קַפְפ",
  "cut (לְגַזוֹר)": "קַט",
  "ear (אזן)": "אֵר",
  "eat (לֶאֱכוֹל)": "אִיט",
  "egg (בֵּיצָה)": "אֶג",
  "end (סוֹף)": "אֶנְד",
  "eye (עַיִן)": "אַי",
  "far (רָחוֹק)": "פַר",
  "fat (שָׁמֵן)": "פַט",
  "fax (פַקְס)": "פַקס",
  "fed (האכיל)": "פֵד",
  "few (מְעַט)": "פְיוּ",
  "fit (מְתֻאָם)": "פִיט",
  "fix (לְתַקֵן)": "פִיקס",
  "fly (לְעוֹף)": "פְלַי",
  "for (לְ)": "פוֹר",
  "fun (כֵּיף)": "פַן",
  "fur (פרווה)": "פֻר",
  "gap (רווח)": "גַפּ",
  "get (לְהַשִׁיג)": "גֵט",
  "got (קִבֵּל)": "גוֹט",
  "gum (מסטיק)": "גַם",
  "gun (רובה)": "גַן",
  "gym (חֲדָר כּוֹשֶׁר)": "גִים",
  "had (הָיָה)": "הַד",
  "hat (כוֹבַע)": "הַט",
  "hay (תֶּבֶן)": "הֵי",
  "hit (לְהַכּוֹת)": "הִיט",
  "hog (חֲזיר בר)": "הוֹג",
  "hot (חָם)": "הוֹט",
  "how (אֵיך)": "הָו",
  "ice (קֶרַח)": "אַיִס",
  "ill (חוֹלֵה)": "אִיל",
  "ink (דְּיוֹ)": "אִינְק",
  "its (שֶׁלוֹ)": "אִיטְס",
  "jam (ריבה)": "ג'ַם",
  "jar (צִנְצֶנֶת)": "ג'ַר",
  "jaw (לֶסֶת)": "ג'וֹ",
  "jet (סילון)": "ג'ֵט",
  "joy (שִׂמְחָה)": "ג'וֹי",
  "key (מַפְתֵּחַ)": "קִי",
  "kit (עֶרְכָּה)": "קִיט",
  "lab (מַעֲבֵדה)": "לָב",
  "lad (בַּחוּר)": "לַד",
  "lag (לְאַחֵר)": "לַג",
  "lap (חֵיק)": "לַפְפ",
  "law (חוֹק)": "לוֹ",
  "lay (לשכב)": "לֵי",
  "leg (רָגֶל)": "לֶג",
  "let (לְתַת)": "לֶט",
  "lid (מכסה)": "לִיד",
  "lie (שֶׁקֶר)": "לַי",
  "lip (שָׂפָה)": "לִיפּ",
  "lit (הָאִיר)": "לִיט",
  "lot (הַרְבֵּה)": "לוֹט",
  "low (נָמוּך)": "לוֹ",
  "mad (מְשׁוּגָע)": "מַד",
  "man (אִישׁ)": "מָן",
  "map (מַפָּה)": "מַפּ",
  "mat (מזרן)": "מַט",
  "mud (בוץ)": "מֻד",
  "mom (אמא)": "מום",
  "mug (סֵפֶל)": "מַג",
  "nap (תְּנוּמָה)": "נַפּ",
  "net (רֶשֶׁת)": "נֵט",
  "new (חָדָשׁ)": "נֵו",
  "nip (לְנַשֵּק)": "נִיפּ",
  "nod (הינהון)": "נוֹד",
  "not (לא)": "נוֹט",
  "now (עַכְשָׁו)": "נָו",
  "oak (אַלּוֹן)": "אוֹק",
  "odd (מוּזָר)": "אָד",
  "off (כבוי)": "אוֹף",
  "oil (שֶׁמֶן)": "אוֹיל",
  "old (זָקֵן)": "אוֹלְד",
  "one (אֶחָד)": "וּוָאן",
  "our (שֶׁלָּנוּ)": "אוּר",
  "out (החוּצָה)": "אוּט",
  "pan (מַחֲבַת)": "פַן",
  "pat (ללטף)": "פַט",
  "pay (לְשַׁלֵּם)": "פֵי",
  "pen (עֵט)": "פֶּן",
  "pet (חיית בית)": "פֶט",
  "pig (חֲזִיר)": "פִיג",
  "pit (בוֹר)": "פִיט",
  "pot (סִיר)": "פוֹט",
  "put (לָשֵׂם)": "פוּט",
  "ran (רָץ)": "רָן",
  "rat (חֹלֶד)": "רַט",
  "raw (נא)": "רָו",
  "ray (רַדִּיו)": "רֵי",
  "red (אָדֹם)": "רֶד",
  "rig (זוֹרֵם)": "רִיג",
  "rim (שֶׂפֶת)": "רִים",
  "rip (לִקְרוֹעַ)": "רִיפּ",
  "rod (מַקֶּלֶת)": "רוֹד",
  "row (שוּרָה)": "רוֹ",
  "rub (לשפשף)": "רֻב",
  "rug (שָׁטִיחַ)": "רַג",
  "run (לָרוּץ)": "רָן",
  "rut (תַּעַלוּת)": "רָט",
  "sad (עָצוּב)": "סַד",
  "sag (לִתֵּל)": "סַג",
  "sap (סאפ)": "סַפּ",
  "sat (יָשַׁב)": "סַט",
  "saw (רָאָה)": "סוֹ",
  "say (לוֹמַר)": "סֵי",
  "see (לִרְאוֹת)": "סִי",
  "set (סט)": "סֵט",
  "sir (אדון)": "סֵיר",
  "she (הִיא)": "שִי",
  "six (שֵׁשׁ)": "סִיקס",
  "ski (סְקִי)": "סְקִי",
  "sky (שָׁמַיִם)": "סְקַי",
  "sly (ערמומי)": "סְלַי",
  "soy (סוֹיה)": "סּוֹי",
  "spy (מרגל)": "סְפָי",
  "sum (סכום)": "סָם",
  "sun (שֶׁמֶשׁ)": "סַן",
  "tab (טאב)": "טַב",
  "tag (תְּוִית)": "טַג",
  "tap (ברז)": "טַפ",
  "tax (מִס)": "טַקְס",
  "tea (תֵּה)": "טֵה",
  "ten (עֲשָׂרָה)": "טֶן",
  "the (הַ)": "דַה",
  "tie (קָשֶׁר)": "טַי",
  "tin (בַּדִיל)": "טִין",
  "tip (קצה)": "טִיפּ",
  "toe (אֶצְבַּע רֶגֶל)": "טֹו",
  "top (עֶלְיוֹן)": "טַפּ",
  "toy (צַעֲצוּעַ)": "טוֹי",
  "try (לְנַסוֹת)": "טְרַי",
  "two (שְׁנַיִם)": "טּוּ",
  "urn (קִיבּוּל)": "אֵרַן",
  "use (לְהִשְׁתַּמֵּשׁ)": "יוּס",
  "van (וָאָן)": "וָאָן",
  "vat (כַּד)": "וַט",
  "vet (וטרינר)": "וֶט",
  "wax (שעווה)": "וַקס",
  "wed (נִשֵּׂא)": "וֶד",
  "wet (רטוב)": "וֶט",
  "win (לִנצח)": "וִין",
  "wit (תְּבוּנָה)": "וִיט",
  "yes (כֵּן)": "יֶס",
  "yet (עדין)": "יֶט",
  "zoo (גַן חיות)": "זוֹ",
};

const WORDS1 = {
  אני: "I",
  אתה: "you",
  את: "you",
  הוא: "he",
  היא: "she",
  אנחנו: "we",
  הם: "they",
  הן: "they",
  זה: "this",
  ההוא: "that",
  היי: "hi",
  או: "or",
  שמש: "sun",
  ירח: "moon",
  כוכב: "star",
  גשם: "rain",
  עכשיו: "now",
  שלג: "snow",
  רוח: "wind",
  עץ: "tree",
  פרח: "flower",
  כלב: "dog",
  חתול: "cat",
  תיק: "bag",
  מיטה: "bed",
  יכול: "can",
  ציפור: "bird",
  כיף: "fun",
  לקבל: "get",
  איש: "man",
  דג: "fish",
  "וְ..": "and",
  אהבה: "love",
  "ה..": "the",
  כן: "yes",
  לא: "no",
  טוב: "good",
  רע: "bad",
  אמא: "mother",
  אבא: "father",
  מיטה: "bed",
  ספר: "book",
  ילד: "boy",
  ילדה: "girl",
  איפה: "where",
  מה: "what",
  מתי: "when",
  איך: "how",
  מי: "who",
  למה: "why",
  שלום: "hello",
  בוקר: "morning",
  פנים: "face",
  בֵּיצָה: "egg",
  סוֹף: "end",
  מסטיק: "gum",
  כוֹבַע: "hat",
  קֶרַח: "ice",
  נָמוּך: "low",
};

const WORDS2 = {
  לילה: "night",
  אוכל: "food",
  מים: "water",
  בבקשה: "please",
  תודה: "thanks",
  סליחה: "sorry",
  אחד: "one",
  שתיים: "two",
  שלוש: "three",
  ארבע: "four",
  חמש: "five",
  שש: "six",
  שבע: "seven",
  שמונה: "eight",
  תשע: "nine",
  עשר: "ten",
  יום: "day",
  שבוע: "week",
  חודש: "month",
  שנה: "year",
  חבר: "friend",
  בית: "house",
  דלת: "door",
  חלון: "window",
  חדר: "room",
  שולחן: "table",
  כיסא: "chair",
  אֲוִיר: "air",
  הַכֹּל: "all",
  זְרוֹעַ: "arm",
  אוּמָנוּת: "art",
  חדשות: "news",
  נייר: "paper",
  עט: "pen",
  תפוח: "apple",
  לחם: "bread",
  חלב: "milk",
  עוף: "chicken",
  דג: "fish",
  פירות: "fruits",
  אוטובוס: "bus",
  מכונית: "car",
  מטוס: "airplane",
  עבודה: "work",
  "בית ספר": "school",
  חנות: "store",
  רחוב: "street",
  עיר: "city",
  ישן: "old",
  בחוץ: "out",
  כפר: "village",
  ים: "sea",
  נהר: "river",
  שמיים: "sky",
  אריה: "lion",
  קוף: "monkey",
  עצוב: "sad",
  חג: "holiday",
  מוזיקה: "music",
  שיר: "song",
  משחק: "game",
  רופא: "doctor",
  משטרה: "police",
  מורה: "teacher",
  רחוק: "far",
  דרך: "way",
  רשת: "web",
  גוף: "body",
};

const ACTIONS = {
  לאכול: "eat",
  לרוץ: "run",
  לראות: "see",
  לומר: "say",
  להוסיף: "add",
  לשאול: "ask",
  לקנות: "buy",
  לחתוך: "cut",
  לחפור: "dig",
  לעשות: "do",
  לגעת: "get",
  לתת: "give",
  ללכת: "go",
  להכות: "hit",
  להחזיק: "hold",
  לקפוץ: "jump",
  לשמור: "keep",
  לשכב: "lay",
  להסתכל: "look",
  לשלם: "pay",
  לשים: "put",
  לקרוא: "read",
  לירות: "shoot",
  לשיר: "sing",
  לשבת: "sit",
  לישון: "sleep",
  לדבר: "speak",
  לעמוד: "stand",
  לשחות: "swim",
  לקחת: "take",
  לספר: "tell",
  לחשוב: "think",
  לזרוק: "throw",
  לנסות: "try",
  לפנות: "turn",
  להשתמש: "use",
  לרחוץ: "wash",
  ללבוש: "wear",
  לנצח: "win",
  לכתוב: "write",
  לבנות: "build",
  לשחק: "play",
  למצוא: "find",
  לשלוח: "send",
  לשנות: "change",
  לצאת: "leave",
  לפתח: "open",
  לסגור: "close",
  לחכות: "wait",
  ללמוד: "learn",
  לעזור: "help",
  לזכור: "remember",
  לשתות: "drink",
  לרקוד: "dance",
  לצייר: "draw",
  לשכוח: "forget",
  לנקות: "clean",
  לצעוק: "shout",
  לצחוק: "laugh",
  לבכות: "cry",
  לנשום: "breathe",
  לגלות: "discover",
  להמציא: "invent",
  לשכנע: "convince",
  לפתח: "develop",
  לשפר: "improve",
  לשתף: "share",
  לצפות: "watch",
  לעבוד: "work",
  לנסוע: "travel",
  לגנוב: "steal",
  להרוג: "kill",
  להציל: "save",
  להתפטר: "quit",
  להתגעגע: "miss",
  להתייאש: "give up",
  להתחרט: "regret",
  להתעצל: "be lazy",
  להתגבר: "overcome",
  להתאים: "fit",
};

const SPORT = {
  כדור: "ball",
  פוטבול: "football",
  כדורגל: "soccer",
  כדורסל: "basketball",
  "כדור בסיס": "baseball",
  "כדור חוף": "beach ball",
  "כדור גולף": "golf ball",
  "פינג פונג": "ping pong",
  רוגבי: "rugby",
  ריצה: "running",
  "ריצת מרתון": "marathon",
  "ריצת ספרינט": "sprint",
  "ריצה קצרה": "short run",
  "ריצה ארוכה": "long run",
  שחייה: "swimming",
  "ספורט מים": "water sport",
  קרב: "fight",
  "קרב מגע": "hand-to-hand combat",
  איגרוף: "boxing",
  קראטה: "karate",
  "ג'ודו": "judo",
  טקוואנדו: "taekwondo",
  היאבקות: "wrestling",
  קיקבוקסינג: "kickboxing",
  "אומנויות לחימה": "martial arts",
  "מאמן קרב": "fight coach",
  "קרב חופשי": "freestyle wrestling",
  תחרות: "competition",
  אימון: "training",
  שחקן: "player",
  מאמן: "coach",
  ניצחון: "victory",
  כושר: "fitness",
  קבוצה: "team",
  משחק: "game",
  אתלטיקה: "athletics",
  מגרש: "field",
  אצטדיון: "stadium",
  מסלול: "track",
  מאמץ: "effort",
  אסטרטגיה: "strategy",
  כישרון: "talent",
  חבטה: "strike",
  גול: "goal",
  שער: "net",
  רשת: "net",
  שופט: "referee",
  "שופט קו": "line judge",
  מזכיר: "secretary",
  "שחקן ספסל": "bench player",
  גיבוי: "backup",
  חלוץ: "forward",
  שוער: "goalkeeper",
  שומר: "defender",
  בלם: "center back",
  קשר: "midfielder",
  צמד: "duo",
  שלישיה: "trio",
  רביעיה: "quartet",
  חמישיה: "quintet",
  מחליף: "substitute",
  חילוף: "substitution",
  עבירה: "foul",
  פנדל: "penalty",
  קנס: "fine",
  אזהרה: "warning",
  הרחקה: "disqualification",
  "כרטיס צהוב": "yellow card",
  "כרטיס אדום": "red card",
  "זמן נוסף": "extra time",
  "חוקי המשחק": "rules",
  מדליה: "medal",
  פרס: "prize",
  גביע: "trophy",
  תוצאה: "score",
  "שער עצמי": "own goal",
  פינה: "corner",
  אזור: "zone",
  זכייה: "win",
  הפסד: "loss",
  תיקו: "draw",
  נקודה: "point",
  "מקום ראשון": "first place",
  "מקום שני": "second place",
  "מקום שלישי": "third place",
  תפיסה: "catch",
  זריקה: "throw",
  בעיטה: "kick",
  קפיצה: "jump",
  "מאמץ מרבי": "maximum effort",
  מגן: "protector",
  קסדה: "helmet",
  ספורט: "sport",
  פוטבול: "football",
  הוקי: "hockey",
  התקפה: "attack",
  הגנה: "defense",
  "מכת פתיחה": "opening blow",
  "הכרעת ניצחון": "knockout",
  "קרב סיבוב": "round fight",
  "מגן שיניים": "mouthguard",
  "חבישת ידיים": "hand wraps",
  "חגורה שחורה": "black belt",
  "הפסד טכני": "technical loss",
  "ניצחון טכני": "technical win",
  טכניקה: "technique",
  "ספירה לאחור": "countdown",
  חגורה: "belt",
  "ספורט חורף": "winter sport",
  "ספורט אתגרי": "extreme sport",
};

const NATURE = {
  עץ: "tree",
  פרח: "flower",
  דשא: "grass",
  אבן: "stone",
  מים: "water",
  שמש: "sun",
  גשם: "rain",
  שלג: "snow",
  ענן: "cloud",
  רוח: "wind",
  ים: "sea",
  אגם: "lake",
  נהר: "river",
  יער: "forest",
  חורש: "woods",
  גבעה: "hill",
  הר: "mountain",
  מדבר: "desert",
  שיח: "bush",
  עציץ: "pot",
  ריחן: "basil",
  "תפוח אדמה": "potato",
  גזר: "carrot",
  קישוא: "zucchini",
  עגבנייה: "tomato",
  תפוח: "apple",
  בננה: "banana",
  תפוז: "orange",
  אגוז: "nut",
  שקד: "almond",
  פירות: "fruits",
  ירקות: "vegetables",
  "עץ פרי": "fruit tree",
  גבעול: "stem",
  עלים: "leaves",
  שורש: "root",
  פטריה: "mushroom",
  חול: "sand",
  "אבן שואבת": "magnet",
  "ים סוער": "stormy sea",
  סלע: "rock",
  כפר: "village",
  מטע: "orchard",
  צמח: "plant",
  חרק: "insect",
  פרפר: "butterfly",
  ציפור: "bird",
  דבורה: "bee",
  עכביש: "spider",
  חפרפרת: "mole",
  תולעת: "worm",
  דג: "fish",
  לטאה: "lizard",
  שועל: "fox",
  ארנב: "rabbit",
  חיה: "animal",
  חוף: "beach",
  "מזג האוויר": "weather",
  יומיים: "day",
  שבוע: "week",
  עונה: "season",
  אביב: "spring",
  קיץ: "summer",
  סתיו: "autumn",
  חורף: "winter",
  "שמש שוקעת": "sunset",
  זריחה: "sunrise",
  כוכב: "star",
  ירח: "moon",
  שמיים: "sky",
  "כוכב לכת": "planet",
  חלל: "space",
  אור: "light",
  צל: "shadow",
  צמחיה: "vegetation",
  מזרח: "east",
  מערב: "west",
  צפון: "north",
  דרום: "south",
  מטר: "meter",
  אדמה: "earth",
};

const COUNTRIES = {
  אוזבקיסטן: "Uzbekistan",
  אוסטרליה: "Australia",
  אוסטריה: "Austria",
  אוקראינה: "Ukraine",
  אורוגוואי: "Uruguay",
  "אזרבייג'אן": "Azerbaijan",
  אינדונזיה: "Indonesia",
  איראן: "Iran",
  אירלנד: "Ireland",
  אלבניה: "Albania",
  "אלג'יריה": "Algeria",
  אנגולה: "Angola",
  אנדורה: "Andorra",
  אסטוניה: "Estonia",
  אפגניסטן: "Afghanistan",
  אקוודור: "Ecuador",
  ארגנטינה: "Argentina",
  ארמניה: "Armenia",
  "ארצות הברית": "United States",
  בוליביה: "Bolivia",
  בנגלדש: "Bangladesh",
  בלגיה: "Belgium",
  בלרוס: "Belarus",
  בריטניה: "United Kingdom",
  ברזיל: "Brazil",
  גאורגיה: "Georgia",
  גבון: "Gabon",
  גרמניה: "Germany",
  גיאנה: "Guyana",
  דנמרק: "Denmark",
  הודו: "India",
  הונגריה: "Hungary",
  הולנד: "Netherlands",
  "הונג קונג": "Hong Kong",
  וונצואלה: "Venezuela",
  ווייטנאם: "Vietnam",
  יוון: "Greece",
  יפן: "Japan",
  ירדן: "Jordan",
  ישראל: "Israel",
  כווית: "Kuwait",
  קולומביה: "Colombia",
  קונגו: "Congo",
  "קוריאה הדרומית": "South Korea",
  "קוריאה הצפונית": "North Korea",
  קזחסטן: "Kazakhstan",
  קטאר: "Qatar",
  קירגיזסטן: "Kyrgyzstan",
  קפריסין: "Cyprus",
  קנדה: "Canada",
  "קוסטה ריקה": "Costa Rica",
  קובה: "Cuba",
  קמבודיה: "Cambodia",
  קמרון: "Cameroon",
  קרואטיה: "Croatia",
  רומניה: "Romania",
  רוסיה: "Russia",
  סוריה: "Syria",
  סינגפור: "Singapore",
  סין: "China",
  סיישל: "Seychelles",
  סלובקיה: "Slovakia",
  סלובניה: "Slovenia",
  ספרד: "Spain",
  "סרי לנקה": "Sri Lanka",
  סרביה: "Serbia",
  "סן מרינו": "San Marino",
  סנגל: "Senegal",
  סודן: "Sudan",
  סורינאם: "Suriname",
  פולין: "Poland",
  פורטוגל: "Portugal",
  "פיג'י": "Fiji",
  פיליפינים: "Philippines",
  פינלנד: "Finland",
  פקיסטן: "Pakistan",
  פרגוואי: "Paraguay",
  פרו: "Peru",
  צרפת: "France",
  "צ'אד": "Chad",
  "צ'ילה": "Chile",
  "צ'כיה": "Czech Republic",
  רואנדה: "Rwanda",
  שוודיה: "Sweden",
  שווייץ: "Switzerland",
  תוניסיה: "Tunisia",
  תימן: "Yemen",
  תורכיה: "Turkey",
  תאילנד: "Thailand",
};

const SENTENCES1 = {
  "אני אוכל תפוח": "I eat an apple",
  "אני רואה כלב": "I see a dog",
  "אני שותה חלב": "I drink milk",
  "אני אוהב דג": "I love fish",
  "אני רץ בפארק": "I run in the park",
  "אני קורא ספר": "I read a book",
  "אני רוכב על אופניים": "I ride a bike",
  "אני מצייר בית": "I draw a house",
  "אני שומע שיר": "I hear a song",
  "אני כותב שם": "I write a name",
  "אני פותח דלת": "I open a door",
  "אני בונה בית": "I build a house",
  "אני מבשל אורז": "I cook rice",
  "אני משחק בכדור": "I play ball",
  "אני מצלם תמונה": "I take a photo",
  "אני מביט בחלון": "I look at the window",
  "אני נוגע בשולחן": "I touch a table",
  "אני לובש כובע": "I wear a hat",
  "אני יושב בכיסא": "I sit on a chair",
  "אני שואל שאלה": "I ask a question",
  "אני מחפש עיפרון": "I look for a pencil",
  "אני קונה עוגה": "I buy a cake",
  "אני אוכל בננה": "I eat a banana",
  "אני פותח ספר": "I open a book",
  "אני מכין תה": "I make tea",
  "אני בוחר צבע": "I choose a color",
  "אני צובע קיר": "I paint a wall",
  "אני מחפש משחק": "I look for a game",
  "אני שומר סוד": "I keep a secret",
  "אני עוזב מקום": "I leave a place",
  "אני כותב מכתב": "I write a letter",
  "אני גוזר נייר": "I cut paper",
  "אני עונה תשובה": "I give an answer",
  "אני נוסע באוטו": "I drive a car",
  "אני שוחה בים": "I swim in the sea",
  "אני מנגן פסנתר": "I play piano",
  "אני לומד עברית": "I learn Hebrew",
  "אני רוקד ריקוד": "I dance a dance",
  "אני יושב על כיסא": "I sit on a chair",
  "אני מצייר פרח": "I draw a flower",
  "אני מטייל בגן": "I walk in the garden",
  "אני קונה פרח": "I buy a flower",
  "אני מחפש מפתח": "I look for a key",
  "אני נוגע בקיר": "I touch the wall",
  "אני מצלם פרח": "I photo a flower",
  "אני אוהב שיר": "I love a song",
  "אני מבשל מרק": "I cook soup",
  "אני לובש מעיל": "I wear a coat",
  "אני רואה עץ": "I see a tree",
  "אני מחפש כסף": "I look for money",
  "אני בונה גשר": "I build a bridge",
  "אני שומע קול": "I hear a voice",
  "אני כותב ספר": "I write a book",
  "אני אוכל תפוח": "I eat an apple",
  "אני רואה כוכב": "I see a star",
  "אני שותה מיץ": "I drink juice",
  "אני מצייר חיה": "I draw an animal",
  "אני שומר חוק": "I keep a rule",
  "אני עוזר חבר": "I help a friend",
  "אני מוצא חפץ": "I find an object",
  "אני לובש נעל": "I wear a shoe",
  "אני צובע קיר": "I paint a wall",
  "אני אוהב עוגה": "I love cake",
  "אני מביט במפה": "I look at the map",
  "אני כותב פתק": "I write a note",
  "אני אופה לחם": "I bake bread",
  "אני בונה גדר": "I build a fence",
  "אני לומד מקצוע": "I learn a subject",
  "אני מדבר בטלפון": "I talk on the phone",
  "אני עובר גשר": "I cross a bridge",
  "אני אוהב תות": "I love strawberry",
  "אני פותח קופסה": "I open a box",
  "אני מחפש מפתח": "I look for a key",
  "אני מדליק אור": "I turn on the light",
  "אני מרים יד": "I raise my hand",
  "אני מרכיב פזל": "I assemble a puzzle",
  "אני נוגע בפרח": "I touch the flower",
  "אני קורא עיתון": "I read a newspaper",
  "אני עוזר ילד": "I help a child",
  "אני שותה תה": "I drink tea",
  "אני רוכב סוס": "I ride a horse",
  "אני בונה אוהל": "I build a tent",
  "אני כותב שם": "I write a name",
  "אני רואה צבע": "I see a color",
  "אני מטפס עץ": "I climb a tree",
  "אני מרים יד": "I raise a hand",
  "אני עובר כביש": "I cross a road",
  "אני נוגע בחול": "I touch the sand",
  "אני עוזר חבר": "I help a friend",
  "אני רץ מהר": "I run fast",
  "אני מחפש שם": "I look for a name",
};

const DD = {
  LETTERS,
  SOUNDS1,
  SOUNDS2,
  WORDS1,
  WORDS2,
  ACTIONS,
  SPORT,
  NATURE,
  COUNTRIES,
  SENTENCES1,
};

export { DD };
